### ISSUE TITLE
Building Lib failed on Raspbian

### ISSUE THREAD

**Issue by DirtySecret** [bibi21000/python-openzwave#93]
Hello,

I'm trying to install the API but it failed when the build of the Lib is running. 
I'm on a Raspberry Pi with Raspbian, I tried with Cython Version 0.14, 0.15 and 0.22 but it made the same and here you can find the information error :

```
python setup-lib.py build
running build
running build_py
package init file 'lib/__init__.py' not found (or not a regular file)
running build_ext
cythoning lib/libopenzwave.pyx to lib/libopenzwave.cpp
```
```
Error compiling Cython file:
------------------------------------------------------------
...
:return: A string containing the library type.
:rtype: str
:see: getLibraryVersion_, getPythonLibraryVersion_, getLibraryTypeName_

        """
        return "OpenZWave version %s" % ozw_version_string
                                                         ^
------------------------------------------------------------
```
```
/home/hepia/git-repo/python-openzwave/lib/libopenzwave.pyx:916:58: Cannot convert 'string' to Python object
building 'libopenzwave' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Iopenzwave/cpp/src -Iopenzwave/cpp/src/value_classes -Iopenzwave/cpp/src/platform -Iopenzwave/cpp/build/linux -I/usr/include/python2.7 -c lib/libopenzwave.cpp -o build/temp.linux-armv6l-2.7/lib/libopenzwave.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]
lib/libopenzwave.cpp:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
error: command 'gcc' failed with exit status 1
Makefile:157: recipe for target 'build' failed
make: *** [build] Error 1
```

What can I do ? 
Thanks for your help

**Comment by nechry** [comment]
I also try, before upgrade to cython 0.15, same error, but with cython 0.22 the compilation completed without error.

**Comment by DirtySecret** [comment]
I will then try again with Cython 0.22

**Comment by DirtySecret** [comment]
In fact, it works with Cython 0.22 ! Thanks again
